### Buscar Categorias
GET http://localhost:3333/api/categories

### Buscar Todas as Tecnologias
GET http://localhost:3333/api/technologies

### Buscar Tecnologia Específica
GET http://localhost:3333/api/technologies/nodejs

### Testar Tecnologia Inexistente (Deve retornar 404)
GET http://localhost:3333/api/technologies/tecnologia-fantasma